name: Legacy App Lint

on:
  push:
    branches:
      - master
    paths:
      - legacy/**
  pull_request:
    branches:
      - master
    paths:
      - legacy/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: legacy/package-lock.json
    - run: npm ci --ignore-scripts
      working-directory: legacy
    - run: npm run lint
      working-directory: legacy
